server:
  port: 8082
spring:
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  config:
    import: "classpath:application-db.yml"
  ssl:
    enabled: true
    key-store: classpath:certificate.jks
    key-store-password: 123456
    key-store-type: JKS
